Added start-farmer and start-node bash scripts
subspace/substrate pull request #12
Opened 2021-08-18 20:20 UTC by ImmaZoni

Added scripts to help users run their farmers and nodes

`./start-farmer.sh` will give the following options:

- Setup/Update Farmer
- Plot 1GB of Data
- Run Farmer
- Wipe Farmer
- Erase Plot
- Exit

`./start-node,sh` will give the following options:

- Setup/Update Node
- Run Full Node
- Kill Node
- Wipe Node
- Exit

These help the user manage the farmers and nodes with less CLI use.

2021-08-18 22:08 UTC, nazar-pc requested changes

2021-08-18 22:08 UTC, nazar-pc commented on bin/node-template-spartan/run-node-farmer-pair.sh
> +export BOOTSTRAP_CLIENT_IP="165.232.157.230"
Why this change?

2021-08-18 22:08 UTC, nazar-pc commented on bin/node-template-spartan/start-farmer.sh
> +setup() {
Please add `set -e` to make sure script aborts at the very first error instead of continuing despite errors

2021-08-18 22:08 UTC, nazar-pc commented on bin/node-template-spartan/start-farmer.sh
> +menu
Please add new line at the end and configure IDE/editor to add new line to all files automatically

2021-08-18 22:08 UTC, nazar-pc commented on bin/node-template-spartan/start-farmer.sh
> +        esac
Can you make this indentation nicer? `case` should start at one level of indentation if I understand it correctly, options should be at 2 levels.

Also please use consistent indentation everywhere, one level should be 4 spaces (this file has a mix of 1, 2, 3 and more spaces).

2021-08-18 22:08 UTC, nazar-pc commented on bin/node-template-spartan/start-farmer.sh
> +$(ColorBlue 'Choose an option:') "
Don't forget to clear colors you no longer need, otherwise things will be rendered inconsistently

2021-08-18 22:28 UTC, ImmaZoni commented on bin/node-template-spartan/run-node-farmer-pair.sh
> +export BOOTSTRAP_CLIENT_IP="165.232.157.230"
It was causing the following error
`Template parsing error: template: :1:18: executing "" at <.NetworkSettings.Networks.spartan.IPAddress>: map has no entry for key "NetworkSettings"`

I believe it is because this was configured for the local network initially which assumed the bootstrap node was local, this is not the case with the bootstrap node being hosted on the dedicated server now. Let me know if I am missing something here.

2021-08-18 22:44 UTC, nazar-pc commented on bin/node-template-spartan/run-node-farmer-pair.sh
> +export BOOTSTRAP_CLIENT_IP="165.232.157.230"
This script was specifically designed to start both local node and local farmer connected to local bootstrap node started using instructions in the readme.

You can make an optional parameter to override IP with whatever is the IP of boostrap node, but I don't think we should hardcode IPs in those scripts either way.

2021-08-18 23:06 UTC, ImmaZoni commented on bin/node-template-spartan/start-farmer.sh
> +$(ColorBlue 'Choose an option:') "
If I am not mistaken the ColorGreen and ColorBlue functions clear them 
```
##
green='\e[32m'
blue='\e[34m'
clear='\e[0m'

##
# Color Functions
##

ColorGreen(){
    echo -ne $green$1$clear
}
ColorBlue(){
    echo -ne $blue$1$clear
}
```

2021-08-18 23:17 UTC, nazar-pc commented on bin/node-template-spartan/start-farmer.sh
> +$(ColorBlue 'Choose an option:') "
Yes, but you don't clear color at the end of the message, so following output might be colored in unexpected ways.

2021-08-19 23:38 UTC, ImmaZoni commented on bin/node-template-spartan/run-node-farmer-pair.sh
> +export BOOTSTRAP_CLIENT_IP="165.232.157.230"
Added a second parameter, if left blank it assumes a local node, if specified with IP, will assume that IP for bootstrap node

2021-08-19 23:46 UTC, nazar-pc commented on bin/node-template-spartan/start-farmer.sh
> +    set +e # disable exit on error, due to the fact the network may be created prior
What you can do instead is to use `command || /bin/true` on a specific command, that will make command not cause script to fail if you expect the command to sometimes return non-zero status code.

2021-08-19 23:46 UTC, nazar-pc commented on bin/node-template-spartan/run-node-farmer-pair.sh
> +echo "${2:-$(docker inspect -f "{{.NetworkSettings.Networks.spartan.IPAddress}}" node-template-spartan)}"
I assume this was used for debugging and is no longer needed?

2021-08-19 23:46 UTC, nazar-pc commented on bin/node-template-spartan/start-farmer.sh
> +        *) echo -e $red"Not a Valid Option, Try Again..."; menu;;
Looks like `$clear` was lost in refactoring, was is intentional?

2021-08-20 00:39 UTC, ImmaZoni commented on bin/node-template-spartan/start-farmer.sh
> +        *) echo -e $red"Not a Valid Option, Try Again..."; menu;;
meant to remove $red aswell. Change posted.

2021-08-20 00:40 UTC, nazar-pc approved these changes

2021-08-23 19:15 UTC, merged